[physics]
useMass = true
mass = -0.5
g = 0.0
kappa = 0.26
lambda = 0.02
cutFraction = 0.0

[langevin]
averageEpsilon = 0.05
MaxLangevinTime = 100.0
ExportTime = 1.0 
burnCount = 1
MeasureDriftCount = 10

[io]
configFileName = "test.hdf"
export = false
timeSliceFileName = "slice.dat"

[random]
seed = 1234
