[physics]
useMass = "false"
mass = 0.0 
g = 0.0
kappa = 0.2
lambda = 0.02
cutFraction = 1.0

[langevin]
averageEpsilon = 0.005
MaxLangevinTime = 5000.0
ExportTime = 1.0
burnCount = 100 
MeasureDriftCount = 20

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 1.1
fermion_mass = 1.2
