[physics]
useMass = "false"
mass = 0.2
g = 1.8
kappa = 0.2
lambda = 0.0
cutFraction = 1.0

[langevin]
averageEpsilon = 0.01
MaxLangevinTime = 1000.0
ExportTime = 1.0
burnCount = 100 
MeasureDriftCount = 50

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 0.6
fermion_mass = 0.75
