[physics]
useMass = "true"
mass = 1.0 
g = 0.5
kappa = 0.28
lambda = 0.02
cutFraction = 0.0

[langevin]
averageEpsilon = 0.01
MaxLangevinTime = 1000.0
ExportTime = 1.0
burnCount = 100 
MeasureDriftCount = 50

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 1.0
fermion_mass = 1.0
