[physics]
useMass = "false"
mass = 0.2
g = 0.0
kappa = 0.3
lambda = 0.02
cutFraction = 1.0

[langevin]
averageEpsilon = 0.05
MaxLangevinTime = 100.0
ExportTime = 1.0 
burnCount = 50
MeasureDriftCount = 50

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling =  1.0
fermion_mass = 1.0
driftMode = 0 # 0 for normal, 1 for rescaled (s^2 times drift)
