[physics]
useMass = "false"
mass = 0.2
g = 0.0
kappa = 0.2
lambda = 0.0
cutFraction = 1.0

[langevin]
averageEpsilon = 0.001
MaxLangevinTime = 100.0
ExportTime = 0.1
burnCount = 500 
MeasureDriftCount = 50

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling =  1.5
fermion_mass = 1.2
driftMode = 0.0 # 0 for normal, 1 for rescaled i.e. s^2 times drift
