[physics]
useMass = "false"
mass = 0.2
g = 1.8
kappa = 0.2
lambda = 0.00
cutFraction = 1.0

[langevin]
averageEpsilon = 0.01
MaxLangevinTime = 5000.0
ExportTime = 1.0
burnCount = 200 
MeasureDriftCount = 50

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 1.1
fermion_mass = 1.2
