[physics]
useMass = "true"
mass = 0.25
g = 0.25
kappa = 0.0
lambda = 0.0
cutFraction = 0.5

[langevin]
averageEpsilon = 0.02
MaxLangevinTime = 1000.0
ExportTime = 1.0
burnCount = 20
MeasureDriftCount = 10

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 0.2
fermion_mass = 5.0
