[physics]
useMass = "false"
mass = -1.0 
g = 0.5
kappa = 0.28
lambda = 0.02
cutFraction = 1.0

[langevin]
averageEpsilon = 0.01
MaxLangevinTime = 1.5
ExportTime = 1.0
burnCount = 0 
MeasureDriftCount = 0

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 1.0
fermion_mass = 1.0
