[physics]
useMass = true
mass = 1.0
g = 0.0
kappa = 0.26
lambda = 0.02
cutFraction = 0.0

[langevin]
averageEpsilon = 0.02
MaxLangevinTime = 10000.0
ExportTime = 10.0
burnCount = 50
MeasureDriftCount = 10

[io]
configFileName = "test.hdf"
export = false
timeSliceFileName = "slice.dat"

[random]
seed = 1234
