[physics]
useMass = true
mass = -1.0
g = 1.0
kappa = 0.26
lambda = 0.02
cutFraction = 1.0

[langevin]
averageEpsilon = 0.02
MaxLangevinTime = 10000.0
ExportTime = 1.0
burnCount = 20
MeasureDriftCount = 10

[io]
configFileName = "test.hdf"
export = false
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 0.0
fermion_mass = 0.4