[physics]
useMass = "true"
mass = -2.0
g = 0.1
kappa = 0.26
lambda = 0.03
cutFraction = 0.0

[langevin]
averageEpsilon = 0.01
MaxLangevinTime = 1000.0
ExportTime = 1.0
burnCount = 30
MeasureDriftCount = 10

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 0.0
fermion_mass = 1.0         
