[physics]
useMass = "true"
mass = -0.125
g = 0.5
kappa = 0.0
lambda = 0.0
cutFraction = 0.0

[langevin]
averageEpsilon = 0.01
MaxLangevinTime = 1000.0
ExportTime = 1.0
burnCount = 20
MeasureDriftCount = 20

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 0.2
fermion_mass = 0.2
