[physics]
useMass = "true"
mass = 0.125
g = 0.25
kappa = 0.0
lambda = 0.0
cutFraction = 0.5

[langevin]
averageEpsilon = 0.01
MaxLangevinTime = 100.0
ExportTime = 1.0
burnCount = 0
MeasureDriftCount = 0

[io]
configFileName = "test.hdf"
export = "false"
timeSliceFileName = "slice.dat"

[random]
seed = 1234

[fermions]
yukawa_coupling = 2.0
fermion_mass = 0.5